from pages.home import show_home
from pages.copy_json_inside_json import show_copy_json
from pages.conversion import show_conversion
from pages.template import show_template
from pages.transformation import show_transformation
from pages.duplicate import show_duplicate
from pages.compare_lists import show_compare_lists
from pages.yaml_key_comparator_page import show_yaml_key_comparator
from pages.url_query_params import show_url_query_params
from pages.combined import show_combined
from pages.filter import show_filter
